# Generated by Django 5.2.4 on 2025-07-28 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyecto',
            new_name='Projects',
        ),
    ]
