# Generated by Django 5.2.4 on 2025-07-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_proyecto_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_type',
            field=models.CharField(choices=[('real', 'Real'), ('simulated', 'Simulated')], default='real', max_length=10),
        ),
    ]
