# Generated by Django 5.2.4 on 2025-07-28 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_projects_project_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='tecnologies',
            new_name='technologies',
        ),
    ]
